### ISSUE TITLE
Typo on example.py and example.swipl

### ISSUE THREAD

**Issue by Nael-Nathanael** [avidito/swifind#1]
Hi, I encountered a typo that prevents the example from executing:

On example.py:
`path = 'exampl.swipl'` should be `path = 'example.swipl'`

On example.swipl:
`IGIN https://quotes.toscrape.com/` should be `ORIGIN https://quotes.toscrape.com/`

**Comment by avidito** [comment]
Thank you so much for your information. I already fix the example script.
